routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\auth\GoogleController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\RolesController;
use App\Http\Controllers\UsersController;
use App\Http\Controllers\ItemsController;
use App\Http\Controllers\BranchesController;
use App\Http\Controllers\StocksController;
use App\Http\Controllers\TransactionsController;
use App\Http\Controllers\PermissionsController;
use App\Http\Controllers\CustomersController;
use App\Http\Controllers\FoodCategoryController;
use App\Http\Controllers\MenuController;
use App\Http\Controllers\OrdersController;
use App\Http\Controllers\CheckoutController;




/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/' );
Route::get('/', [HomeController::class, 'index'])->name('home');
Route::get('/about-us', [HomeController::class, 'aboutus'])->name('about-us');
Route::get('/services', [HomeController::class, 'services'])->name('services');
Route::get('/contact', [HomeController::class, 'contact'])->name('contact');
Route::get('/customer-menu', [HomeController::class, 'menu'])->name('customer-menu');

Auth::routes();
Route::get('auth/google', [GoogleController::class, 'redirectToGoogle']);
Route::get('auth/google/callback', [GoogleController::class, 'handleGoogleCallback']);


Route::group(['namespace' => '\App\Http\Controllers'], function () {

    Route::get('dashboard', [DashboardController::class, 'index'])->name('dashboard');
   // Route::redirect('/', '/login')->name('home');
    // Permissions
    Route::delete('permissions/destroy', [PermissionsController::class, 'massDestroy'])->name('permissions.massDestroy');
    Route::resource('permissions', 'PermissionsController');

    // Roles
    Route::delete('roles/destroy', 'RolesController@massDestroy')->name('roles.massDestroy');
    Route::resource('roles', 'RolesController');

    // Users
    Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');
    Route::resource('users', 'UsersController');

    // Items
    Route::delete('items/destroy', 'ItemsController@massDestroy')->name('items.massDestroy');
    Route::resource('items', 'ItemsController');

    // Branches
    Route::delete('branches/destroy', 'BranchesController@massDestroy')->name('branches.massDestroy');
    Route::resource('branches', 'BranchesController');

    // Stocks
    //Route::delete('stocks/destroy', 'StocksController@massDestroy')->name('stocks.massDestroy');
    Route::resource('stocks', 'StocksController')->only(['index', 'show']);

    // Transactions
    // Route::delete('transactions/destroy', 'TransactionsController@massDestroy')->name('transactions.massDestroy');
    Route::post('transactions/{stock}/storeStock', 'TransactionsController@storeStock')->name('transactions.storeStock');
    Route::resource('transactions', 'TransactionsController')->only(['index']);

    //customers
    Route::resource('customers', 'CustomersController');

    //food categories
    Route::resource('foodcategories', 'FoodCategoryController');

    //menu
    Route::resource('menu', 'MenuController');

    //Orders
    Route::resource('orders', 'OrdersController');

});

//cart

    Route::get('cart', [CheckoutController::class, 'cart'])->name('cart');
    Route::get('add-to-cart/{id}', [CheckoutController::class, 'addToCart'])->name('add.to.cart');
    Route::post('update-cart', [CheckoutController::class, 'update'])->name('update.cart');
    Route::post('remove-from-cart', [CheckoutController::class, 'remove'])->name('remove.from.cart');
    Route::get('place-order', [CheckoutController::class, 'placeOrder'])->name('place-order');
    Route::post('checkout-order', [CheckoutController::class, 'checkoutOrder'])->name('checkout-order');

// Route::group(['prefix' => 'profile', 'as' => 'profile.', 'namespace' => 'Auth', 'middleware' => ['auth']], function () {
// // Change password
//     if (file_exists(app_path('Http/Controllers/Auth/ChangePasswordController.php'))) {
//         Route::get('password', 'ChangePasswordController@edit')->name('password.edit');
//         Route::post('password', 'ChangePasswordController@update')->name('password.update');
//     }

// });

app/Models/FoodCategory.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class FoodCategory extends Model
{
    use HasFactory;
    protected $fillable = [
        'name',
        'description',
        'status'
    ];
}

app/Http/Controllers/FoodCategoryController.php
<?php

namespace App\Http\Controllers;

use App\Models\FoodCategory;
use App\Http\Requests\StoreFoodCategoryRequest;
use App\Http\Requests\UpdateFoodCategoryRequest;

//Gate
use Gate;

use Symfony\Component\HttpFoundation\Response;

class FoodCategoryController extends Controller
{
    public function index()
    {
        abort_if(Gate::denies('food category access'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $food_categories = FoodCategory::all();
        return view('admin.foodcategories.index', compact('food_categories'));

    }

    public function create()
    {
        abort_if(Gate::denies('food_category_create'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('admin.foodcategories.create');
    }

    public function store(StoreFoodCategoryRequest $request)
    {
        $food_category = FoodCategory::create($request->all());

        return redirect()->route('foodcategories.index');

    }

    public function edit(FoodCategory $foodcategory)
    {

        abort_if(Gate::denies('Edit Food Category'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('admin.foodcategories.edit', compact('foodcategory'));
    }

    public function update(UpdateFoodCategoryRequest $request, FoodCategory $foodcategory)
    {
        $foodcategory->update($request->all());

        return redirect()->route('foodcategories.index');

    }

    public function show(FoodCategory $foodcategory)
    {
        abort_if(Gate::denies('food_category_show'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('admin.foodcategories.show', compact('foodcategory'));
    }

    public function destroy(FoodCategory $foodcategory)
    {
        abort_if(Gate::denies('Delete Food Category'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $foodcategory->delete();

        return back();

    }

    public function massDestroy(MassDestroyFoodCategoryRequest $request)
    {
        FoodCategory::whereIn('id', request('ids'))->delete();

        return response(null, Response::HTTP_NO_CONTENT);

    }

}

resources/views/admin/foodcategories/edit.blade.php
@extends('admin.layouts.admin')
@section('content')

<div class="row">
<div class="content-wrapper-before gradient-45deg-indigo-purple"></div>
<div class="breadcrumbs-dark pb-0 pt-4" id="breadcrumbs-wrapper">
  <!-- Search for small screen-->
</div>
    <div class="col s12">
        <div class="container">
            <div class="seaction">
            <!-- Form with validation -->
                <div class="col s12 m12 l12">
                    <div id="form-with-validation" class="card card card-default scrollspy">
                        <div class="card-content">
                            <h4 class="card-title">Edit Food Category</h4>
                                <form method="POST" action="{{ route('foodcategories.update', [$foodcategory->id]) }}" enctype="multipart/form-data">
                                    @method('PUT')
                                    @csrf
                                    <div class="form-group">
                                        <label class="required" for="name">{{ trans('cruds.item.fields.name') }}</label>
                                        <input class="form-control {{ $errors->has('name') ? 'is-invalid' : '' }}" type="text" name="name" id="name" value="{{ old('name', $foodcategory->name) }}" required>
                                        @if($errors->has('name'))
                                            <div class="invalid-feedback">
                                                {{ $errors->first('name') }}
                                            </div>
                                        @endif
                                        <span class="help-block">{{ trans('cruds.item.fields.name_helper') }}</span>
                                    </div>
                                    <div class="form-group">
                                        <label class="required" for="description">{{ trans('cruds.item.fields.description') }}</label>
                                        <input class="form-control {{ $errors->has('description') ? 'is-invalid' : '' }}" type="text" name="description" id="description" value="{{ old('description', $foodcategory->description) }}" required>
                                        @if($errors->has('description'))
                                            <div class="invalid-feedback">
                                                {{ $errors->first('description') }}
                                            </div>
                                        @endif
                                        <span class="help-block">{{ trans('cruds.item.fields.name_helper') }}</span>
                                    </div>
                                    <div class="form-group">
                                        <div class="input-field">
                                          <select class="select2-size-sm browser-default" id="small-select" name="status">
                                            <option value="1">Active</option>
                                            <option value="2">Inactive</option>
                                          </select>
                                        </div>           
                                    </div>
                                    <div class="form-group">
                                        <button class="btn btn-danger" type="submit">
                                            {{ trans('global.save') }}
                                        </button>
                                    </div>
                                </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
<div class="content-overlay"></div>
</div>
@endsection

resources/views/admin/foodcategories/index.blade.php
@extends('admin.layouts.admin')
@section('content')

<div class="row">
    <div class="content-wrapper-before gradient-45deg-indigo-purple"></div>
      <div class="breadcrumbs-dark pb-0 pt-4" id="breadcrumbs-wrapper">
          <!-- Search for small screen-->
          <div class="container">
            <div class="row">
              <div class="col s10 m6 l6">
                <h5 class="breadcrumbs-title mt-0 mb-0"><span>Users List</span></h5>
                <ol class="breadcrumbs mb-0">
                  <li class="breadcrumb-item"><a href="index.html">Home</a>
                  </li>
                  <li class="breadcrumb-item"><a href="#">User</a>
                  </li>
                  <li class="breadcrumb-item active">Users List
                  </li>
                </ol>
              </div>
              @can('user_create')
              <div class="col s2 m6 l6"><a href="#add-foodcategory-modal" class="btn waves-effect waves-light breadcrumbs-btn right modal-trigger"><span class="hide-on-small-onl">{{ trans('global.add') }} Food Categories</span></a>                
              </div>
              @endcan
            </div>
          </div>
        </div>
        <div class="col s12">
        <div class="container">
        <!-- users list start -->
        <section class="users-list-wrapper section">
          <div class="users-list-filter">
            <div class="card-panel">
              <div class="row">
                <form>
                  <div class="col s12 m6 l3">
                    <label for="users-list-verified">Verified</label>
                    <div class="input-field">
                      <select class="form-control" id="users-list-verified">
                        <option value="">Any</option>
                        <option value="Yes">Yes</option>
                        <option value="No">No</option>
                      </select>
                    </div>
                  </div>
                  <div class="col s12 m6 l3">
                    <label for="users-list-role">Role</label>
                    <div class="input-field">
                      <select class="form-control" id="users-list-role">
                        <option value="">Any</option>
                        <option value="User">User</option>
                        <option value="Staff">Staff</option>
                      </select>
                    </div>
                  </div>
                  <div class="col s12 m6 l3">
                    <label for="users-list-status">Status</label>
                    <div class="input-field">
                      <select class="form-control" id="users-list-status">
                        <option value="">Any</option>
                        <option value="Active">Active</option>
                        <option value="Close">Close</option>
                        <option value="Banned">Banned</option>
                      </select>
                    </div>
                  </div>
                  <div class="col s12 m6 l3 display-flex align-items-center show-btn">
                    <button type="submit" class="btn btn-block indigo waves-effect waves-light">Show</button>
                  </div>
                </form>
              </div>
            </div>
          </div>
          <div class="users-list-table">
            <div class="card">
              <div class="card-content">
                <!-- datatable start -->
                <div class="responsive-table">
                  <table id="users-list-datatable" class="table">
                <thead>
                    <tr>
                      <th>
                        Id
                      </th>
                        <th>
                            Name
                        </th>
                        
                        <th>
                            {{ trans('cruds.item.fields.description') }}
                        </th>
                        <th>
                          Status
                        </th>
                        <th>
                          Edit
                        </th>
                        <th>
                          Delete
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($food_categories as $key => $category)
                        <tr data-entry-id="{{ $category->id }}">
                            <td>
                                {{ $category->id }}
                            </td>
                            <td>
                               {{ $category->name }}
                            </td>
                            <td>
                                {{ $category->description }}
                            </td>
                            <td>
                              <?php if ($category->status ==  1) {
                                echo "Active";
                              }
                              else{
                                echo "Inactive";
                              } ?>
                            </td>
                              <td>
                                @can('item_edit')
                                    <a  href="{{ route('foodcategories.edit', $category->id) }}">
                                        <i class="material-icons">edit</i>
                                    </a>
                                @endcan
                              </td>
                            
                            <td>

                                @can('item_delete')
                                    <form action="{{ route('foodcategories.destroy', $category->id) }}" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block;">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <input type="submit" class="btn btn-xs btn-danger" value="{{ trans('global.delete') }}">
                                    </form>
                                @endcan

                            </td>

                        </tr>
                    @endforeach
                </tbody>
                </table>
                </div>
                <!-- datatable ends -->
              </div>
            </div>
          </div>
        </section>
      </div>
      <div class="content-overlay"></div>
    </div>
  </div>
</div>
@endsection

<div id="add-foodcategory-modal" class="modal modal-fixed-footer">
  <div class="modal-content">
    <h4>Add Customer</h4>
    <form method="POST" action="{{ route('foodcategories.store') }}" enctype="multipart/form-data">
            @csrf
            <div class="form-group">
                <label class="required" for="name">Name</label>
                <input class="form-control {{ $errors->has('name') ? 'is-invalid' : '' }}" type="text" name="name" id="name" value="{{ old('name', '') }}" required>
                @if($errors->has('name'))
                    <div class="invalid-feedback">
                        {{ $errors->first('name') }}
                    </div>
                @endif
                
            </div>

             <div class="form-group">
                <label class="required" for="mobile-no">Description</label>
                <input class="form-control {{ $errors->has('description') ? 'is-invalid' : '' }}" type="text" name="description" id="description" value="{{ old('description', '') }}" required>
                @if($errors->has('description'))
                    <div class="invalid-feedback">
                        {{ $errors->first('description') }}
                    </div>
                @endif
               
            </div>

             <div class="form-group">
                <div class="input-field">
                  <select class="select2-size-sm browser-default" id="small-select" name="status">
                    <option value="1">Active</option>
                    <option value="2">Inactive</option>
                  </select>
                </div>           
            </div>

            <div class="form-group">
              
                <button class="btn btn-danger" type="submit">
                    {{ trans('global.save') }}
                </button>
            </div>
        </form>
  </div>
  <div class="modal-footer">
    <a href="#!" class="modal-action modal-close waves-effect waves-green btn-flat ">Close</a>
  </div>
</div>